<a href="https://colab.research.google.com/github/nghiaduc177/Pytorch-Tutorial/blob/main/Torch_basic_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
import numpy as np

In [2]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.81908795, 0.65043383, 0.30781014, 0.62411896],
       [0.20596471, 0.43859779, 0.26565245, 0.95960528],
       [0.65599404, 0.74527242, 0.63994177, 0.37827638]])

In [6]:
np1.dtype

dtype('float64')

In [10]:
tensor_2d = torch.randn(3,4)
tensor_2d
tensor_2d.dtype

torch.float32

In [8]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.8191, 0.6504, 0.3078, 0.6241],
        [0.2060, 0.4386, 0.2657, 0.9596],
        [0.6560, 0.7453, 0.6399, 0.3783]], dtype=torch.float64)